FROM python:3.9-slim

WORKDIR /app

COPY recommender-service/requirements.txt .
RUN apt-get update && apt-get install -y gcc g++ curl && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt


COPY recommender-service/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]